server:
  port: 8082

spring:
  application:
    name: rocketmq-test

rocketmq:
  producer:
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    maxMessageSize: 4096
    sendMsgTimeOut: 3000
    retryTimesWhenSendFailed: 2
  consumer:
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    consumeThreadMin: 4
    consumeThreadMax: 32
    consumeMessageBatchMaxSize: 1
    reConsumeTimes: 3